name: Build
on:
  push:
  workflow_dispatch:

jobs:
  deploy-pipeline:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Initialize project
        run: echo "ready"
